# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
---
jobs:
  aur:
    container: # https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
      credentials:
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_PRIVATE_KEY_B64: ${{ secrets.GPG_PRIVATE_KEY_B64 }}
      image: josecardoso/archlinux:aur
    runs-on: ubuntu-latest
    steps:
      - run: git -C /tmp clone ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git
      - run: /tmp/aur/aur.sh
name: aur
on:
  push:
    paths:
      - aur.sh
      - packages.txt
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:
