# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
---
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # https://github.com/actions/checkout
        with:
          fetch-depth: 0 # Disable Shallow Clone
      - name: Docker Hub Login
        uses: docker/login-action@v2 # https://github.com/docker/login-action
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v2 # https://github.com/docker/setup-buildx-action
      - name: Docker Build/Push
        uses: docker/build-push-action@v2 # https://github.com/docker/build-push-action
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/archlinux:aur
name: docker
on:
  push:
    paths:
      - .github/workflows/docker.yaml
      - Dockerfile
